name: flutter_mobile_template
description: Flutter Mobile App Template

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  #Text
  google_fonts: ^3.0.1
  auto_size_text: ^3.0.0


  #Responsive
  responsive_sizer: ^3.1.1

  #Image
  flutter_svg: ^1.1.6

  #State Management
  provider: ^6.0.5
  flutter_bloc: ^8.1.1

  #FreezedAnnotation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  #Equality Operator
  equatable: ^2.0.5

  #Network
  vexana: ^3.1.1
  url_launcher: ^6.1.7


  #Locale Storage
  flutter_secure_storage: ^7.0.1
  hive_flutter:

  #Navigation
  go_router: ^6.0.0

  #Localization
  intl: ^0.17.0
  easy_localization: ^3.0.1
  bot_toast: ^4.0.3

  #Firebase
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  google_sign_in: ^5.4.2
  firebase_storage: ^11.0.8
  cloud_firestore: ^4.2.0

  #Native Splash Screen
  flutter_native_splash: ^2.2.16


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  # Code generation
  build_runner: ^2.3.3
  hive_generator:

  # Freezed code generation
  freezed: ^2.3.2

  # Native Launcher Icons generator
  flutter_launcher_icons: ^0.11.0

  # Change app package name/bundle id and app name
  change_app_package_name: ^1.1.0
  rename: ^2.0.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/